ServerEvents.recipes((event) => {
    //龙魂锻炉
    //龙之星
    event.custom(
        {"type":"chaosworld_core:dragon_soul_forging",
            "itemInputs":[
                {"ingredient":{"item":"ifeu:rough_dragon_star"},"count":1}
            ],
            "fluidInputs":[
                {"fluid":"create_enchantment_industry:infused_dragon_breath","amount":1000}
            ],
            "catalystInput":{
                "ingredient":{"item":"chaosworld_core:dragon_catalyst"},
                "amount":1,
                "consume":false
            },
            "output":{"id":"ifeu:dragon_star","count":1}}
    )
    //龙炎钢锭
    event.custom(
        {"type":"chaosworld_core:dragon_soul_forging",
            "itemInputs":[
                {"ingredient":{"item":"chaosworld_core:ingot_tech_6"},"count":1},
                {"ingredient":{"item":"iceandfire:fire_dragon_blood"},"count":1}
            ],
            "fluidInputs":[
                {"fluid":"modularbees:dragon_breath","amount":1000}
            ],
            "catalystInput":{
                "ingredient":{"tag":"iceandfire:scales/dragon/fire"},
                "amount":1,
                "consume":true
            },
            "output":{"id":"iceandfire:dragonsteel_fire_ingot","count":1}}
    )
    //龙霜钢锭
    event.custom(
        {"type":"chaosworld_core:dragon_soul_forging",
            "itemInputs":[
                {"ingredient":{"item":"chaosworld_core:ingot_tech_6"},"count":1},
                {"ingredient":{"item":"iceandfire:ice_dragon_blood"},"count":1}
            ],
            "fluidInputs":[
                {"fluid":"modularbees:dragon_breath","amount":1000}
            ],
            "catalystInput":{
                "ingredient":{"tag":"iceandfire:scales/dragon/ice"},
                "amount":1,
                "consume":true
            },
            "output":{"id":"iceandfire:dragonsteel_ice_ingot","count":1}}
    )
    //龙霆钢锭
    event.custom(
        {"type":"chaosworld_core:dragon_soul_forging",
            "itemInputs":[
                {"ingredient":{"item":"chaosworld_core:ingot_tech_6"},"count":1},
                {"ingredient":{"item":"iceandfire:lightning_dragon_blood"},"count":1}
            ],
            "fluidInputs":[
                {"fluid":"modularbees:dragon_breath","amount":1000}
            ],
            "catalystInput":{
                "ingredient":{"tag":"iceandfire:scales/dragon/lightning"},
                "amount":1,
                "consume":true
            },
            "output":{"id":"iceandfire:dragonsteel_lightning_ingot","count":1}}
    )
    //无尽锭
    event.custom(
        {"type":"chaosworld_core:dragon_soul_forging",
            "itemInputs":[
                {"ingredient":{"item":"extendedcrafting:the_ultimate_ingot"},"count":16},
                {"ingredient":{"item":"ufo:white_dwarf_fragment_ingot"},"count":3},
                {"ingredient":{"item":"ufo:neutron_star_fragment_ingot"},"count":3},
                {"ingredient":{"item":"ufo:pulsar_fragment_ingot"},"count":3},
                {"ingredient":{"item":"chaosworld_core:ingot_xuancai"},"count":3},
                {"ingredient":{"item":"chaosworld_core:holy_gold_ingot"},"count":3}
            ],
            "fluidInputs":[
                {"fluid":"ufo:source_spatial_fluid","amount":1000}
            ],
            "catalystInput":{
                "ingredient":{"item":"avaritia:infinity_catalyst"},
                "amount":1,
                "consume":false
            },
            "output":{"id":"avaritia:infinity_ingot","count":9}}
    )
})
