name = "ChaosWorld"
author = "yongaishide"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d96b7a0e5793c2ec3ba31661968e8a4c07ab9e8384104ec6e1f123d0c727ac4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"