name = "ChaosWorld"
author = "yongaishide"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc7c42db268ae006056ff9bdea5a657181bad2293c7f0bf6c787f0b6e6e1a20b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"