# Config for this game installation.

# Name: jei.config.modIdFormat.modName
# Description: jei.config.modIdFormat.modName.description
[modName]
	# Name: jei.config.modIdFormat.modName.modNameFormat
	# Description: jei.config.modIdFormat.modName.modNameFormat.description
	# Valid Values: A bracketed list containing values of:
	# [BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC]
	# List requirements:
	# A list containing values of:
	# [BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC]
	# Default Value: ["BLUE","ITALIC"]
	modNameFormat = ["BLUE","ITALIC"]


