# Config for this game installation.

# Name: jei.config.debug.debug
# Description: jei.config.debug.debug.description
[debug]
	# Name: jei.config.debug.debug.debugIngredientsEnabled
	# Description: jei.config.debug.debug.debugIngredientsEnabled.description
	# Valid Values: [true, false]
	# Default Value: false
	debugIngredientsEnabled = false

	# Name: jei.config.debug.debug.debugGuis
	# Description: jei.config.debug.debug.debugGuis.description
	# Valid Values: [true, false]
	# Default Value: false
	debugGuis = false

	# Name: jei.config.debug.debug.debugInputs
	# Description: jei.config.debug.debug.debugInputs.description
	# Valid Values: [true, false]
	# Default Value: false
	debugInputs = false

	# Name: jei.config.debug.debug.debugInfoTooltipsEnabled
	# Description: jei.config.debug.debug.debugInfoTooltipsEnabled.description
	# Valid Values: [true, false]
	# Default Value: false
	debugInfoTooltipsEnabled = false

	# Name: jei.config.debug.debug.logSuffixTreeStats
	# Description: jei.config.debug.debug.logSuffixTreeStats.description
	# Valid Values: [true, false]
	# Default Value: false
	logSuffixTreeStats = false


