ServerEvents.recipes((event) => {
    //品红物质
    event.custom(
        {"type":"mekanism:painting",
            "chemical_input":{"amount":3200,"chemical":"mekanism:magenta"},
            "item_input":{"count":1,"item":"ufo:proto_matter"},
            "output":{"count":1,"id":"projectexpansion:magenta_matter"},
            "per_tick_usage":false}
    )
    //粉物质
    event.custom(
        {"type":"mekanism:painting",
            "chemical_input":{"amount":3200,"chemical":"mekanism:pink"},
            "item_input":{"count":1,"item":"ufo:proto_matter"},
            "output":{"count":1,"id":"projectexpansion:pink_matter"},
            "per_tick_usage":false}
    )
    //紫物质
    event.custom(
        {"type":"mekanism:painting",
            "chemical_input":{"amount":3200,"chemical":"mekanism:purple"},
            "item_input":{"count":1,"item":"ufo:proto_matter"},
            "output":{"count":1,"id":"projectexpansion:purple_matter"},
            "per_tick_usage":false}
    )
    //蓝物质
    event.custom(
        {"type":"mekanism:painting",
            "chemical_input":{"amount":3200,"chemical":"mekanism:blue"},
            "item_input":{"count":1,"item":"ufo:proto_matter"},
            "output":{"count":1,"id":"projectexpansion:blue_matter"},
            "per_tick_usage":false}
    )
    //青物质
    event.custom(
        {"type":"mekanism:painting",
            "chemical_input":{"amount":3200,"chemical":"mekanism:cyan"},
            "item_input":{"count":1,"item":"ufo:proto_matter"},
            "output":{"count":1,"id":"projectexpansion:cyan_matter"},
            "per_tick_usage":false}
    )
    //绿物质
    event.custom(
        {"type":"mekanism:painting",
            "chemical_input":{"amount":3200,"chemical":"mekanism:green"},
            "item_input":{"count":1,"item":"ufo:proto_matter"},
            "output":{"count":1,"id":"projectexpansion:green_matter"},
            "per_tick_usage":false}
    )
    //黄绿物质
    event.custom(
        {"type":"mekanism:painting",
            "chemical_input":{"amount":3200,"chemical":"mekanism:lime"},
            "item_input":{"count":1,"item":"ufo:proto_matter"},
            "output":{"count":1,"id":"projectexpansion:lime_matter"},
            "per_tick_usage":false}
    )
    //黄物质
    event.custom(
        {"type":"mekanism:painting",
            "chemical_input":{"amount":3200,"chemical":"mekanism:yellow"},
            "item_input":{"count":1,"item":"ufo:proto_matter"},
            "output":{"count":1,"id":"projectexpansion:yellow_matter"},
            "per_tick_usage":false}
    )
    //橙物质
    event.custom(
        {"type":"mekanism:painting",
            "chemical_input":{"amount":3200,"chemical":"mekanism:orange"},
            "item_input":{"count":1,"item":"ufo:proto_matter"},
            "output":{"count":1,"id":"projectexpansion:orange_matter"},
            "per_tick_usage":false}
    )
    //白物质
    event.custom(
        {"type":"mekanism:painting",
            "chemical_input":{"amount":3200,"chemical":"mekanism:white"},
            "item_input":{"count":1,"item":"ufo:proto_matter"},
            "output":{"count":1,"id":"projectexpansion:white_matter"},
            "per_tick_usage":false}
    )
    //红物质
    event.custom(
        {"type":"mekanism:painting",
            "chemical_input":{"amount":3200,"chemical":"mekanism:red"},
            "item_input":{"count":1,"item":"ufo:proto_matter"},
            "output":{"count":1,"id":"projecte:red_matter"},
            "per_tick_usage":false}
    )
})