# Config for this game installation.

# Name: mezz_config.config.fileWatcher
# Description: mezz_config.config.fileWatcher.description
[fileWatcher]
	# Name: mezz_config.config.fileWatcher.enabled
	# Description: mezz_config.config.fileWatcher.enabled.description
	# Valid Values: [true, false]
	# Default Value: true
	# Requires a game restart to take effect.
	enabled = true

	# Name: mezz_config.config.fileWatcher.changeSettlingDelayMilliseconds
	# Description: mezz_config.config.fileWatcher.changeSettlingDelayMilliseconds.description
	# Valid Values: Any long greater than or equal to 1
	# Default Value: 500
	# Requires a game restart to take effect.
	changeSettlingDelayMilliseconds = 500

	# Name: mezz_config.config.fileWatcher.missingDirectoryRetryIntervalMilliseconds
	# Description: mezz_config.config.fileWatcher.missingDirectoryRetryIntervalMilliseconds.description
	# Valid Values: Any long greater than or equal to 1
	# Default Value: 60000
	# Requires a game restart to take effect.
	missingDirectoryRetryIntervalMilliseconds = 60000


# Name: mezz_config.config.logging
# Description: mezz_config.config.logging.description
[logging]
	# Name: mezz_config.config.logging.logUntranslatedKeys
	# Description: mezz_config.config.logging.logUntranslatedKeys.description
	# Valid Values: [true, false]
	# Default Value: false
	# Requires a game restart to take effect.
	logUntranslatedKeys = false


