[Gameplay]
	#Makes Orange Trees behave consistently with Sweet Berry Bushes
	"Orange Tree consistency" = false
	#Changes the message sent on attacking the Slider with an incorrect item to an alternate version which more subtly implies that you need a pickaxe
	"Improved Slider Message" = true
	#Allows a smaller, tan variation of Zephyrs to spawn
	"Tan Zephyr variant" = true
