#Color for tech_1 items (hex ARGB)
techColor_1 = -2066430
#Color for tech_2 items (hex ARGB)
techColor_2 = -9681338
#Color for tech_3 items (hex ARGB)
techColor_3 = -16568524
#Color for tech_4 items (hex ARGB)
techColor_4 = -16523667
#Color for tech_5 items (hex ARGB)
techColor_5 = -7123032
#Color for tech_6 items (hex ARGB)
techColor_6 = -7643914
#Color for tech_7 items (hex ARGB)
techColor_7 = -1292135
#Color for tech_8 items (hex ARGB)
techColor_8 = -680437
#Color for tech_9 items (hex ARGB)
techColor_9 = -1096636
