[General]
	#是否允许玩家自定义【物品导管】的抽取频率（1~200 tick）。
	enableItemCustomFrequency = true
	#是否允许玩家自定义【流体导管】的抽取频率（1~200 tick）。
	enableFluidCustomFrequency = true
	#是否允许玩家自定义【化学品导管】的抽取频率（1~200 tick）。
	enableChemicalCustomFrequency = true
