	[cursedItems.totemOfMalice]
		# Default: 80
		# Range: 0 ~ 200
		specialDamageBoost = 80
		# Default: 50
		# Range: 0 ~ 100
		specialDamageResistance = 50

	[cursedItems.enderSlayer]
		# Default: 150
		# Range: 0 ~ 1000
		specialDamageBoost = 150

	[cursedItems.nightScroll]
		# Default: 16
		# Range: 1 ~ 64
		effectiveRange = 16
		# Default: 20
		# Range: 0 ~ 100
		attackDamage = 20
		# Default: 16
		# Range: 0 ~ 100
		damageResistance = 16
		# Default: 8
		# Range: 0 ~ 100
		lifeSteal = 8

	[cursedItems.cursedXpScroll]
		# Default: 24.0
		# Range: 1.0 ~ 256.0
		magneticRange = 24.0
		# Default: 1000
		# Range: 100 ~ 32768
		xpLevelUpperLimit = 1000
		# Default: 128.0
		# Range: 0.0 ~ 256.0
		damageBoostLimit = 128.0
		# Default: 64.0
		# Range: 0.0 ~ 256.0
		healBoostLimit = 64.0
		# Default: 160.0
		# Range: 0.0 ~ 256.0
		knockbackResistanceBoostLimit = 160.0

	[cursedItems.cursedScroll]
		# Default: 4
		# Range: 1 ~ 20
		attackDamage = 4
		# Default: 4
		# Range: 0 ~ 20
		miningSpeed = 4
		# Default: 4
		# Range: 1 ~ 20
		regeneration = 4
		# Default: 0.1
		# Range: 0.0 ~ 1.0
		decayFactor = 0.1

	[cursedItems.avariceScroll]
		# Default: 15
		# Range: 0 ~ 100
		emeraldChance = 15

	[cursedItems.guardianHeart]
		# Default: 24.0
		# Range: 4.0 ~ 64.0
		effectiveRange = 24.0
		# Default: 200
		# Range: 100 ~ 600
		cooldown = 200

	[cursedItems.berserkEmblem]
		# Default: 1.0
		# Range: 0.0 ~ 10.0
		attackDamage = 1.0
		# Default: 1.0
		# Range: 0.0 ~ 10.0
		attackSpeed = 1.0
		# Default: 0.5
		# Range: 0.0 ~ 10.0
		movementSpeed = 0.5
		# Default: 0.5
		# Range: 0.0 ~ 1.0
		damageResistance = 0.5

	[cursedItems.theTwist]
		# Default: 300
		# Range: 0 ~ 1000
		specialDamageBoost = 300
		# Default: 300
		# Range: 0 ~ 1000
		knockbackModifier = 300

	[cursedItems.sanguinaryHandbook]
		# Default: 0.25
		# Range: 0.0 ~ 1.0
		specialDamageBoost = 0.25

[else]
	freezingBoost = true

	[else.starlightBucket]
		checkExtraContent = false

	[else.majesticElytra]
		# Default: 75
		# Range: 0 ~ 95
		resistanceModifier = 75

	[else.ichorSpear]
		# Default: 4
		# Range: 0 ~ 12
		baseDamage = 4
		# Default: 600
		# Range: 0 ~ 1200
		duration = 600
		# Default: 1
		# Range: 0 ~ 4
		amplifier = 1

	[else.executionAxe]
		# Default: 10
		# Range: 0 ~ 50
		beheadingBase = 10
		# Default: 5
		# Range: 0 ~ 20
		beheadingBonus = 5

	[else.xpScroll]
		# Default: 16.0
		# Range: 1.0 ~ 256.0
		magneticRange = 16.0

	[else.survivorScroll]
		# Default: 40
		# Range: 0 ~ 100
		healthThreshold = 40

	[else.explorerScroll]
		# Default: 5
		# Range: 1 ~ 10
		effectiveRange = 5
		# Default: 320
		# Range: 160 ~ 800
		cooldown = 320

	[else.cosmicScroll]
		# Default: 12000
		# Range: 6000 ~ 24000
		cooldown = 12000
		# Default: 32
		# Range: 0 ~ 100
		spellstoneCooldown = 32

	[else.starlightRing]
		# Default: 30
		# Range: 0 ~ 100
		specialDamageResistance = 30

	[else.quartzRing]
		# Default: 25
		# Range: 0 ~ 100
		specialDamageResistance = 25

	[else.magnetRing]
		# Default: 8.0
		# Range: 1.0 ~ 256.0
		magneticRange = 8.0

	[else.infernalRing]
		# Default: 60
		# Range: 0 ~ 100
		specialDamageResistance = 60

	[else.dislocation]
		# Default: 16.0
		# Range: 1.0 ~ 256.0
		magneticRange = 16.0

	[else.storageCrystal]
		enable = true

	[else.void_stone]
		devourBlacklist = ["enigmaticlegacyplus:void_stone", "sophisticatedbackpacks:backpack", "sophisticatedbackpacks:copper_backpack", "sophisticatedbackpacks:iron_backpack", "sophisticatedbackpacks:gold_backpack", "sophisticatedbackpacks:diamond_backpack", "sophisticatedbackpacks:netherite_backpack"]

	[else.antiqueBag]
		extraBookList = []

	[else.hellBladeCharm]
		# Default: 100
		# Range: 0 ~ 200
		attackDamage = 100
		# Default: 100
		# Range: 0 ~ 100
		armorDebuff1 = 100

	[else.forgerGem]
		# Default: 20
		# Range: 0 ~ 100
		breakChanceModifier = 20
		# Default: 4
		# Range: 0 ~ 20
		extraDurabilityModifier = 4
		# Default: 20
		# Range: 0 ~ 100
		extraMaxDurability = 20

	[else.odeToLiving]
		# Default: 24.0
		# Range: 4.0 ~ 96.0
		effectiveRange = 24.0
		# Default: 50
		# Range: 0 ~ 100
		specialDamageResistance = 50
		# Default: 1200
		# Range: 200 ~ 2000
		cooldown = 1200

	[else.hunterGuidebook]
		# Default: 16.0
		# Range: 4.0 ~ 64.0
		effectiveRange = 16.0

	[else.enigmaticAmulet]
		# Default: 2.0
		# Range: 0.0 ~ 10.0
		amuletRed = 2.0
		# Default: 15
		# Range: 0 ~ 100
		amuletAqua = 15
		# Default: 15
		# Range: 0 ~ 100
		amuletViolet = 15
		# Default: 20
		# Range: 0 ~ 100
		amuletMagenta = 20
		# Default: 2.0
		# Range: 0.0 ~ 10.0
		amuletGreen = 2.0
		# Default: 10
		# Range: 0 ~ 100
		amuletBlack = 10
		# Default: 25
		# Range: 0 ~ 100
		amuletBlue = 25

[abyssItems]
	# Default: 5
	# Range: 1 ~ 10
	abyssalHeartCount = 5
	# Default: 0.995
	# Range: 0.0 ~ 1.0
	abyssThreshold = 0.995

	[abyssItems.chaosElytra]
		# Default: 80
		# Range: 0 ~ 100
		specialDamageResistance = 80
		# Default: 0.8
		# Range: 0.5 ~ 5.0
		flyingSpeedModifier = 0.8
		# Default: 1.6
		# Range: 1.0 ~ 10.0
		descendingPowerModifier = 1.6
		# Default: 500
		# Range: 200 ~ 1200
		descendingCooldown = 500

	[abyssItems.violenceScroll]
		# Default: 4
		# Range: 0 ~ 10
		attackSpeed = 4
		# Default: 3
		# Range: 0 ~ 20
		entityReach = 3
		# Default: 2
		# Range: 0 ~ 10
		knockbackResistanceBoost = 2

	[abyssItems.desolationRing]
		# Default: 64
		# Range: 1 ~ 128
		effectiveRange = 64
		# Default: 240
		# Range: 20 ~ 1200
		cooldown = 240

	[abyssItems.theInfinitum]
		# Default: 200
		# Range: 0 ~ 1000
		specialDamageBoost = 200
		# Default: 200
		# Range: 0 ~ 1000
		knockbackModifier = 200
		# Default: 10
		# Range: 0 ~ 100
		lifeSteal = 10
		# Default: 80
		# Range: 0 ~ 100
		undeadProbability = 80

	[abyssItems.eldritchAmulet]
		# Default: 20
		# Range: 0 ~ 100
		attackDamage = 20
		# Default: 15
		# Range: 0 ~ 100
		lifeSteal = 15
		keepInventory = true

	[spellstone.voidPearl]
		# Default: 16.0
		# Range: 0.0 ~ 128.0
		shadowRange = 16.0
		# Default: 4
		# Range: 0 ~ 100
		darknessDamage = 4
		# Default: 2
		# Range: 0 ~ 10
		witheringLevel = 2
		# Default: 5.0
		# Range: 0.0 ~ 120.0
		witheringTime = 5.0
		# Default: 30
		# Range: 0 ~ 80
		undeadProbability = 30

	[spellstone.theCube]
		# Default: 100.0
		# Range: 0.0 ~ 1000.0
		damageLimit = 100.0
		autoTrigger = true

	[spellstone.revivalLeaf]
		# Default: 5
		# Range: 1 ~ 40
		naturalRegenerationSpeed = 5
		# Default: 2.0
		# Range: 1.0 ~ 20.0
		vulnerabilityModifier = 2.0
		# Default: 120
		# Range: 60 ~ 240
		cooldown = 120

	[spellstone.oceanStone]
		# Default: 40
		# Range: 0 ~ 100
		underwaterCreaturesResistance = 40
		# Default: 1.0
		# Range: 0.0 ~ 10.0
		xpCostModifier = 1.0
		preventOxygenBarRender = false
		# Default: 2.0
		# Range: 1.0 ~ 20.0
		vulnerabilityModifier = 2.0
		# Default: 600
		# Range: 200 ~ 1000
		cooldown = 600

	[spellstone.lostEngine]
		# Default: 50
		# Range: 0 ~ 200
		bonusCritMultiplier = 50
		# Default: 2.5
		# Range: 1.0 ~ 20.0
		vulnerabilityModifier = 2.5

	[spellstone.illusionLantern]
		# Default: 1.25
		# Range: 1.0 ~ 20.0
		vulnerabilityModifier = 1.25
		# Default: 50
		# Range: 0 ~ 80
		resistanceModifier = 50
		# Default: 60
		# Range: 20 ~ 200
		cooldown = 60

	[spellstone.golemHeart]
		# Default: 4.0
		# Range: 0.0 ~ 20.0
		defaultArmorBonus = 4.0
		# Default: 16.0
		# Range: 0.0 ~ 100.0
		superArmorBonus = 16.0
		# Default: 4.0
		# Range: 0.0 ~ 20.0
		superArmorToughnessBonus = 4.0
		# Default: 0.9
		# Range: 0.0 ~ 1.0
		knockbackResistance = 0.9
		# Default: 25
		# Range: 0 ~ 100
		meleeResistance = 25
		# Default: 40
		# Range: 0 ~ 100
		explosionResistance = 40
		# Default: 2.0
		# Range: 1.0 ~ 20.0
		vulnerabilityModifier = 2.0

	[spellstone.forgottenIce]
		# Default: 30
		# Range: 0 ~ 100
		resistanceModifier = 30
		# Default: 4.0
		# Range: 0.0 ~ 64.0
		damageFeedback = 4.0
		# Default: 2.5
		# Range: 1.0 ~ 20.0
		vulnerabilityModifier = 2.5
		# Default: 240
		# Range: 100 ~ 400
		cooldown = 240

	[spellstone.eyeOfNebula]
		# Default: 40
		# Range: 0 ~ 100
		magicBoost = 40
		# Default: 65
		# Range: 0 ~ 100
		magicResistance = 65
		# Default: 15
		# Range: 0 ~ 100
		dodgeProbability = 15
		# Default: 150
		# Range: 0 ~ 1000
		attackEmpower = 150
		# Default: 2.0
		# Range: 1.0 ~ 20.0
		vulnerabilityModifier = 2.0
		# Default: 60
		# Range: 20 ~ 200
		cooldown = 60

	[spellstone.etheriumCore]
		# Default: 32
		# Range: 0 ~ 100
		etheriumThresholdModifier = 32
		# Default: 40
		# Range: 0 ~ 100
		damageConversion = 40
		# Default: 25
		# Range: 0 ~ 100
		damageConversionLimit = 25

	[spellstone.creationHeart]
		# Default: 3
		# Range: 1 ~ 40
		cooldown = 3

	[spellstone.blazingCore]
		# Default: 4.0
		# Range: 0.0 ~ 64.0
		damageFeedback = 4.0
		# Default: 4
		# Range: 0 ~ 32
		ignitionFeedback = 4
		# Default: 2.0
		# Range: 1.0 ~ 20.0
		vulnerabilityModifier = 2.0

	[spellstone.angelBlessing]
		# Default: 1.0
		# Range: 0.0 ~ 256.0
		accelerationModifier = 1.0
		# Default: 0.6
		# Range: 0.0 ~ 256.0
		accelerationModifierElytra = 0.6
		# Default: 40
		# Range: 0 ~ 100
		deflectChance = 40
		# Default: 2.0
		# Range: 1.0 ~ 20.0
		vulnerabilityModifier = 2.0
		# Default: 30
		# Range: 10 ~ 100
		cooldown = 30

	[blessItems.redemptionRing]
		# Default: 25
		# Range: 0 ~ 100
		damageMultiplier = 25
		# Default: 20
		# Range: 0 ~ 100
		attackMultiplier = 20
		# Default: 20
		# Range: 5 ~ 100
		regenerationSpeed = 20
		# Default: 1
		# Range: 0 ~ 8
		lootingBonusAlt = 1
		# Default: 1
		# Range: 0 ~ 8
		fortuneBonusAlt = 1
		enableSpecialDrops = true
		uniqueLegacy = true

	[blessItems.earthPromise]
		# Default: 1000
		# Range: 200 ~ 2000
		cooldown = 1000
		# Default: 25
		# Range: 0 ~ 100
		firstCurseModifier = 25
		# Default: 80
		# Range: 0 ~ 100
		healthThreshold = 80

	[blessItems.scorchedCharm]
		# Default: 2
		# Range: 0 ~ 10
		lavaHealAmount = 2
		# Default: 20
		# Range: 0 ~ 100
		lifestealModifier = 20
		# Default: 10
		# Range: 0 ~ 50
		resistanceProbability = 10

	[blessItems.theBless]
		# Default: 0.15
		# Range: 0.0 ~ 1.0
		specialDamageBoost = 0.15

[sevenCurses]
	# Default: 200
	# Range: 100 ~ 500
	painMultiplier = 200
	# Default: 24.0
	# Range: 4.0 ~ 100.0
	neutralAngerRange = 24.0
	# Default: 30
	# Range: 0 ~ 100
	armorDebuff = 30
	# Default: 40
	# Range: 0 ~ 100
	monsterDamageDebuff = 40
	eternalBurning = true
	#Allowed Values: ALWAYS_LOSS, NEED_CURSE_RING, NEED_CURSE_RING_AND_IGNORE_KEEPINVENTORY
	soulCrystalsMode = "NEED_CURSE_RING"
	enableInsomnia = true
	# Default: 1
	# Range: 0 ~ 10
	lootingBonus = 1
	# Default: 1
	# Range: 0 ~ 10
	fortuneBonus = 1
	# Default: 300
	# Range: 0 ~ 1000
	experienceBonus = 300
	# Default: 10
	# Range: 0 ~ 30
	enchantingBonus = 10
	enableSpecialDrops = true
	enableEnderRing = true
	uniqueLegacy = true
	autoEquip = false
	ultraHardcore = false
	# Default: 9
	# Range: 0 ~ 10
	maxSoulCrystalLoss = 9
	forTheWorthy = true
	giveStarterGear = true
	neutralWhiteList = ["minecraft:bee", "the_bumblezone:bee_queen"]
