#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 06 17:40:47 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.8.1 + EuphoriaPatches_1.9.3
