#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 07 00:26:54 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.9 + EuphoriaPatches_1.10.0
