#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 27 21:05:23 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.9 + EuphoriaPatches_1.10.0
