[OblivionKeystone]
	#Soft cap for Keystone of the Oblivion. When it's reached, the list view seen in its Ctrl tooltip
	#will be fixed at this amount of items and become chaotic and unreadable. Required since monitors
	#are not infinitely large these days.
	# Default: 25
	# Range: > 1
	softcap = 25
	#Hard cap for Keystone of the Oblivion. When it's reached, you will no longer be able to add new
	#items to its list via crafting. Required to prevent potential performance issues with
	#ridiculously large lists.
	# Default: 250
	# Range: > 1
	hardcap = 250

[MagnetRings]
	#The radius, in blocks, in which the Magnetic Ring attracts items.
	# Default: 8.0
	# Range: 1.0 ~ 256.0
	magnetRange = 8.0
	#The radius, in blocks, in which the Dislocation Ring collects items.
	# Default: 16.0
	# Range: 1.0 ~ 256.0
	dislocationRange = 16.0
