#是否启用Powah充能台输入槽堆叠功能（附属功能）
#开启后充能台的输入槽可以放入多个相同物品（最多64个），配方匹配会将物品数量计入
#需要Powah mod作为前置
#Enable Powah energizing orb input stacking (addon feature)
#When enabled, input slots can hold multiple items (up to 64), recipe matching accounts for item count
#Requires Powah mod
enableEnergizingStacking = true
#Cable Orb max energy receive rate for Starter tier (FE/t)
# Default: 100
# Range: 1 ~ 9223372036854775807
cableOrbTransferStarter = 100
# Default: 400
# Range: 1 ~ 9223372036854775807
cableOrbTransferBasic = 400
# Default: 1000
# Range: 1 ~ 9223372036854775807
cableOrbTransferHardened = 1000
# Default: 4000
# Range: 1 ~ 9223372036854775807
cableOrbTransferBlazing = 4000
# Default: 10000
# Range: 1 ~ 9223372036854775807
cableOrbTransferNiotic = 10000
# Default: 40000
# Range: 1 ~ 9223372036854775807
cableOrbTransferSpirited = 40000
# Default: 200000
# Range: 1 ~ 9223372036854775807
cableOrbTransferNitro = 200000
