ServerEvents.recipes((event) => {
    //四阶科技粉
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_items":[
                {"amount":4,"ingredient":{"item":"chaosworld_core:dust_tech_3"}},
                {"amount":3,"ingredient":{"item":"enderio:grains_of_infinity"}},
                {"amount":2,"ingredient":{"item":"extendedae:entro_dust"}}
            ],
            "output":{"count":4,"id":"chaosworld_core:dust_tech_4"}}
    )
    //1k元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":1,"ingredient":{"item":"ae2omnicells:omni_link_processor"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"chaosworld_core:plate_tech_1"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_1k"}}
    )
    //4k元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_cell_component_1k"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_link_processor"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_4k"}}
    )
    //16k元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_cell_component_4k"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_link_processor"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_16k"}}
    )
    //64k元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_cell_component_16k"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_link_processor"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_64k"}}
    )
    //256k元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_cell_component_64k"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_link_processor"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_256k"}}
    )
    //4k元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_link_processor"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"chaosworld_core:plate_tech_1"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_4k"}}
    )
    //16k元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":4,"ingredient":{"item":"ae2omnicells:omni_link_processor"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"chaosworld_core:plate_tech_2"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_16k"}}
    )
    //64k元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":8,"ingredient":{"item":"ae2omnicells:omni_link_processor"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"chaosworld_core:plate_tech_2"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_64k"}}
    )
    //256k元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":32,"ingredient":{"item":"ae2omnicells:omni_link_processor"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"chaosworld_core:plate_tech_3"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_256k"}}
    )
    //1M元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_cell_component_256k"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_link_processor"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_1m"}}
    )
    //1M元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":2,"ingredient":{"item":"chaosworld_core:circuit_processor"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"chaosworld_core:plate_tech_3"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_1m"}}
    )
    //4M元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_cell_component_1m"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_link_processor"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_4m"}}
    )
    //4M元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":4,"ingredient":{"item":"chaosworld_core:circuit_processor"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"chaosworld_core:plate_tech_4"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_4m"}}
    )
    //16M元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_cell_component_4m"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_link_processor"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_16m"}}
    )
    //16M元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":8,"ingredient":{"item":"chaosworld_core:circuit_processor"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"chaosworld_core:plate_tech_4"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_16m"}}
    )
    //64M元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_cell_component_16m"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_link_processor"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_64m"}}
    )
    //64M元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":16,"ingredient":{"item":"chaosworld_core:circuit_processor"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"chaosworld_core:plate_tech_5"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_64m"}}
    )
    //256M元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_cell_component_64m"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"ae2omnicells:omni_link_processor"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_256m"}}
    )
    //256M元件组件
    event.custom(
        {"type":"extendedae:crystal_assembler",
            "input_fluid":{"amount":100,"ingredient":{"fluid":"minecraft:water"}},
            "input_items":[
                {"amount":32,"ingredient":{"item":"chaosworld_core:circuit_processor"}},
                {"amount":3,"ingredient":{"item":"ae2omnicells:ender_ingot"}},
                {"amount":2,"ingredient":{"item":"chaosworld_core:plate_tech_5"}}
            ],
            "output":{"count":1,"id":"ae2omnicells:omni_cell_component_256m"}}
    )
})