ServerEvents.recipes((event) => {
    event.custom(
        {"type":"immersiveengineering:arc_furnace",
            "additives":[],
            "energy":51200,
            "input":{"tag":'c:dusts/hop_graphite'},
            "results":[{"item":"immersiveengineering:ingot_hop_graphite"}],
            "time":100}
    )
    event.custom(
        {"type":"immersiveengineering:arc_furnace",
            "additives":[],
            "energy":51200,
             "input":{"basePredicate":{"tag":'c:ingots/construction_alloy'},"count":2},
             "results":[{"item":"extendedcrafting:black_iron_ingot"}],
            "secondaries":[{"chance":0.5,"output":{"item":"mekanism:dirty_dust_iron"}}],
            "time":100}
    )
    event.custom(
        {"type":"immersiveengineering:arc_furnace",
            "additives":[{"basePredicate":{"item":"minecraft:smooth_stone"},"count":4}],
            "energy":51200,
            "input":{"basePredicate":{"tag":'c:ingots/compressed_iron'},"count":1},
            "results":[{"basePredicate":{"item":"pneumaticcraft:reinforced_stone"},"count":4}],
            "time":100}
    )
    //二阶科技锭
    event.custom(
        {"type":"immersiveengineering:arc_furnace",
            "additives":[
                {"basePredicate":{"item":"enderio:redstone_alloy_ingot"},"count":1},
                {"basePredicate":{"item":"immersiveengineering:dust_coke"},"count":2}
            ],
            "energy":51200,
            "input":{"basePredicate":{"tag":'c:ingots/crude_steel'},"count":1},
            "results":[{"basePredicate":{"item":"chaosworld_core:ingot_tech_2"},"count":2}],
            "time":100}
    )
    //三阶科技锭
    event.custom(
        {"type":"immersiveengineering:arc_furnace",
            "additives":[
                {"basePredicate":{"item":"minecraft:netherite_scrap"},"count":2},
                {"basePredicate":{"item":"pneumaticcraft:ingot_iron_compressed"},"count":3}
            ],
            "energy":51200,
            "input":{"basePredicate":{"tag":'c:ingots/dark_steel'},"count":3},
            "results":[{"basePredicate":{"item":"chaosworld_core:ingot_tech_3"},"count":3}],
            "time":100}
    )
    //流明精华
    event.custom(
        {"type":"immersiveengineering:arc_furnace",
            "additives":[
                {"basePredicate":{"item":"alltheores:lumium_dust"},"count":1},
                {"basePredicate":{"item":"naturesaura:gold_powder"},"count":1}
            ],
            "energy":51200,
            "input":{"basePredicate":{"item":"mysticalagriculture:tertium_essence"},"count":1},
            "results":[{"basePredicate":{"item":"extendedcrafting:luminessence"},"count":1}],
            "time":100}
    )
    //末影锭
    event.custom(
        {"type":"immersiveengineering:arc_furnace",
            "additives":[
                {"basePredicate":{"item":"rainbowcompound:enderite_ingot"},"count":2},
                {"basePredicate":{"item":"enderio:ender_crystal_powder"},"count":1}
            ],
            "energy":51200,
            "input":{"basePredicate":{"item":"enderio:pulsating_alloy_ingot"},"count":3},
            "results":[{"basePredicate":{"item":"alltheores:enderium_ingot"},"count":3}],
            "time":100}
    )

})