ServerEvents.recipes((event) => {
    event.custom(
        {"type":"alloy_smelter:smelting",
            "ingredients":[
                {"ingredient":{"item":"extendedcrafting:redstone_ingot"},"count":1},
                {"ingredient":{"item":"enderio_evolution:construction_alloy_ingot"},"count":1},
                {"ingredient":{"item":"ae2:silicon"},"count":2}
            ],
            "result":{"id":"enderio:redstone_alloy_ingot","count":2},
            "smeltingTime":100,
            "fuelPerTick":1,
            "requiredTier":2}
    )
    event.custom(
        {"type":"alloy_smelter:smelting",
            "ingredients":[
                {"ingredient":{"item":"extendedcrafting:redstone_ingot"},"count":1},
                {"ingredient":{"item":"enderio_evolution:construction_alloy_ingot"},"count":1},
                {"ingredient":{"item":"ae2:silicon"},"count":2}
            ],
            "result":{"id":"enderio:redstone_alloy_ingot","count":2},
            "smeltingTime":60,
            "fuelPerTick":1,
            "requiredTier":3}
    )
    //一阶科技锭
    event.custom(
        {"type":"alloy_smelter:smelting",
            "ingredients":[
                {"ingredient":{"item":"alltheores:electrum_ingot"},"count":1},
                {"ingredient":{"item":"alltheores:constantan_ingot"},"count":1},
                {"ingredient":{"item":"ae2:certus_quartz_dust"},"count":2}
            ],
            "result":{"id":"chaosworld_core:ingot_tech_1","count":2},
            "smeltingTime":140,
            "fuelPerTick":1,
            "requiredTier":1}
    )
    //一阶科技锭
    event.custom(
        {"type":"alloy_smelter:smelting",
            "ingredients":[
                {"ingredient":{"item":"alltheores:electrum_ingot"},"count":1},
                {"ingredient":{"item":"alltheores:constantan_ingot"},"count":1},
                {"ingredient":{"item":"ae2:certus_quartz_dust"},"count":2}
            ],
            "result":{"id":"chaosworld_core:ingot_tech_1","count":2},
            "smeltingTime":100,
            "fuelPerTick":1,
            "requiredTier":2}
    )
    //一阶科技锭
    event.custom(
        {"type":"alloy_smelter:smelting",
            "ingredients":[
                {"ingredient":{"item":"alltheores:electrum_ingot"},"count":1},
                {"ingredient":{"item":"alltheores:constantan_ingot"},"count":1},
                {"ingredient":{"item":"ae2:certus_quartz_dust"},"count":2}
            ],
            "result":{"id":"chaosworld_core:ingot_tech_1","count":2},
            "smeltingTime":60,
            "fuelPerTick":1,
            "requiredTier":3}
    )
    //二阶科技锭
    event.custom(
        {"type":"alloy_smelter:smelting",
            "ingredients":[
                {"ingredient":{"item":"enderio:redstone_alloy_ingot"},"count":1},
                {"ingredient":{"item":"enderio_evolution:crude_steel_ingot"},"count":1},
                {"ingredient":{"item":"immersiveengineering:dust_coke"},"count":2}
            ],
            "result":{"id":"chaosworld_core:ingot_tech_2","count":2},
            "smeltingTime":140,
            "fuelPerTick":1,
            "requiredTier":1}
    )
    //二阶科技锭
    event.custom(
        {"type":"alloy_smelter:smelting",
            "ingredients":[
                {"ingredient":{"item":"enderio:redstone_alloy_ingot"},"count":1},
                {"ingredient":{"item":"enderio_evolution:crude_steel_ingot"},"count":1},
                {"ingredient":{"item":"immersiveengineering:dust_coke"},"count":2}
            ],
            "result":{"id":"chaosworld_core:ingot_tech_2","count":2},
            "smeltingTime":100,
            "fuelPerTick":1,
            "requiredTier":2}
    )
    //二阶科技锭
    event.custom(
        {"type":"alloy_smelter:smelting",
            "ingredients":[
                {"ingredient":{"item":"enderio:redstone_alloy_ingot"},"count":1},
                {"ingredient":{"item":"enderio_evolution:crude_steel_ingot"},"count":1},
                {"ingredient":{"item":"immersiveengineering:dust_coke"},"count":2}
            ],
            "result":{"id":"chaosworld_core:ingot_tech_2","count":2},
            "smeltingTime":60,
            "fuelPerTick":1,
            "requiredTier":3}
    )
})
